name: 'Call composite action checkout dynamic versioning'

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: text
        default: main

jobs:
  call_composite_action:
    runs-on: ubuntu-latest
    name: 'Call composite action checkout static versioning'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: kyanny-corp-enterprise-cloud-testing/zd-1669617-called-repo-1
          ref: ${{inputs.version}}
          path: zd-1669617-called-repo-1
      - run: ls -lah
      - run: tree .
      - uses: ./zd-1669617-called-repo-1/.github/actions
