name: 'Call composite action static versioning'

on:
  push:
  workflow_dispatch:

jobs:
  call_composite_action:
    runs-on: ubuntu-latest
    name: 'Call composite action static versioning'
    steps:
      - uses: kyanny-corp-enterprise-cloud-testing/zd-1669617-called-repo-1/.github/actions@v1
