name: 'Composite action checkout dynamic'

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: text

jobs:
  call_composite_action:
    runs-on: ubuntu-latest
    name: 'Composite action checkout dynamic'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: kyanny-corp-enterprise-cloud-testing/zd-1669617-called-repo-1
          ref: ${{ inputs.version }}
          path: zd-1669617-called-repo-1
      - uses: ./zd-1669617-called-repo-1/.github/actions
