name: 'Composite action uses dynamic'

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: text

jobs:
  call_composite_action:
    runs-on: ubuntu-latest
    name: 'Composite action uses dynamic'
    steps:
      - uses: kyanny-corp-enterprise-cloud-testing/zd-1669617-called-repo-1/.github/actions@${{ inputs.version }}
